# Generated by Django 5.2.13 on 2026-04-27 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='starlinkorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='telegramconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='starlinkorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='telegramconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='starlinkpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Tchad', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='starlink_kit_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pin_verified', 'PIN Verified'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='starlinkpackage',
            name='data_limit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='starlinkpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='telegramconfig',
            name='bot_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='telegramconfig',
            name='chat_id',
            field=models.CharField(max_length=100),
        ),
    ]
